spring:
  datasource:
    url: jdbc:mysql://localhost/workflow?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
flowable:
  async-executor-activate: false

server:
  port: 8082



