spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crystal?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  type-handlers-package: com.tiny.springbootmybatisxml.dao
mybatis.
