spring:
  datasource:
    url: jdbc:mysql://localhost/flowabledb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
flowable:
  async-executor-activate: false

server:
  port: 8080
management:
  endpoint:
    flowable:
      enabled: true

