spring:
  datasource:
    url: jdbc:mysql://localhost/workflow?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform:  org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
flowable:
  async-executor-activate: false

server:
  port: 8082



