spring:
  datasource:
    url: jdbc:mysql://localhost/flowabledb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
flowable:
  async-executor-activate: false

server:
  port: 8082